name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android packages
        run: |
          sdkmanager "platform-tools"
          sdkmanager "platforms;android-35"
          sdkmanager "build-tools;35.0.0"
          sdkmanager "ndk;27.3.13750724"

      - name: Install system dependencies
        run: |
          sudo apt-get update

          sudo apt-get install -y \
            build-essential \
            git \
            zip \
            unzip \
            python3-pip \
            python3-dev \
            autoconf \
            automake \
            autopoint \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            cmake \
            libffi-dev \
            libssl-dev \
            lbzip2

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade buildozer
          python3 -m pip install "cython==0.29.37"

      - name: Show Android environment
        run: |
          echo "ANDROID_HOME=$ANDROID_HOME"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
          java -version
          python3 --version
          buildozer --version

      - name: Clean Buildozer
        run: |
          rm -rf .buildozer
          rm -rf bin
          mkdir -p bin

      - name: Build APK
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
          ANDROID_SDK_ROOT: ${{ env.ANDROID_HOME }}
        run: |
          yes | buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Task-Planner-APK
          path: bin/*.apk
