name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update

          sudo apt-get install -y \
            build-essential \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            python3-dev \
            autoconf \
            automake \
            autopoint \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            cmake \
            libffi-dev \
            libssl-dev \
            lbzip2

      - name: Set Java 17
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64" >> $GITHUB_ENV
          echo "/usr/lib/jvm/temurin-17-jdk-amd64/bin" >> $GITHUB_PATH

      - name: Check environment
        run: |
          python3 --version
          pip3 --version
          gcc --version
          g++ --version
          java -version

      - name: Install Buildozer
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade buildozer
          python3 -m pip install "cython==0.29.37"

      - name: Clean previous Buildozer files
        run: |
                   rm -rf .buildozer
                   rm -rf bin
                   mkdir -p bin
      - name: Build APK
        run: |
          yes | buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Task-Planner-APK
          path: bin/*.apk
